import { Network, type NetworkInfo, type NetworkMode } from "@/types/wallet";

export const NETWORKS: Record<Network, NetworkInfo> = {
	// ============ MAINNETS ============
	[Network.ETHEREUM]: {
		id: Network.ETHEREUM,
		name: "Ethereum",
		symbol: "ETH",
		chainId: 1,
		rpcUrl: "https://eth.drpc.org",
		explorerUrl: "https://etherscan.io",
		icon: "⟠",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: false,
	},
	[Network.POLYGON]: {
		id: Network.POLYGON,
		name: "Polygon",
		symbol: "POL",
		chainId: 137,
		rpcUrl: "https://polygon.drpc.org",
		explorerUrl: "https://polygonscan.com",
		icon: "🟣",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: false,
	},
	[Network.BSC]: {
		id: Network.BSC,
		name: "BNB Smart Chain",
		symbol: "BNB",
		chainId: 56,
		rpcUrl: "https://bsc.drpc.org",
		explorerUrl: "https://bscscan.com",
		icon: "🟡",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: false,
	},
	[Network.ARBITRUM]: {
		id: Network.ARBITRUM,
		name: "Arbitrum One",
		symbol: "ETH",
		chainId: 42161,
		rpcUrl: "https://arbitrum.drpc.org",
		explorerUrl: "https://arbiscan.io",
		icon: "🔵",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: false,
	},
	[Network.OPTIMISM]: {
		id: Network.OPTIMISM,
		name: "Optimism",
		symbol: "ETH",
		chainId: 10,
		rpcUrl: "https://optimism.drpc.org",
		explorerUrl: "https://optimistic.etherscan.io",
		icon: "🔴",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: false,
	},
	[Network.AVALANCHE]: {
		id: Network.AVALANCHE,
		name: "Avalanche",
		symbol: "AVAX",
		chainId: 43114,
		rpcUrl: "https://avalanche.drpc.org",
		explorerUrl: "https://snowtrace.io",
		icon: "🔺",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: false,
	},
	[Network.BASE]: {
		id: Network.BASE,
		name: "Base",
		symbol: "ETH",
		chainId: 8453,
		rpcUrl: "https://base.drpc.org",
		explorerUrl: "https://basescan.org",
		icon: "🔷",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: false,
	},
	[Network.SOLANA]: {
		id: Network.SOLANA,
		name: "Solana",
		symbol: "SOL",
		rpcUrl: "https://api.mainnet-beta.solana.com",
		explorerUrl: "https://solscan.io",
		icon: "◎",
		isEVM: false,
		decimals: 9,
		derivationPath: "m/44'/501'/0'/0'",
		isTestnet: false,
	},
	[Network.BITCOIN]: {
		id: Network.BITCOIN,
		name: "Bitcoin",
		symbol: "BTC",
		rpcUrl: "",
		explorerUrl: "https://blockstream.info",
		icon: "₿",
		isEVM: false,
		decimals: 8,
		derivationPath: "m/84'/0'/0'/0/0",
		isTestnet: false,
	},

	// ============ TESTNETS ============
	[Network.ETHEREUM_SEPOLIA]: {
		id: Network.ETHEREUM_SEPOLIA,
		name: "Ethereum Sepolia",
		symbol: "ETH",
		chainId: 11155111,
		rpcUrl: "https://sepolia.drpc.org",
		explorerUrl: "https://sepolia.etherscan.io",
		icon: "⟠",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: true,
	},
	[Network.POLYGON_AMOY]: {
		id: Network.POLYGON_AMOY,
		name: "Polygon Amoy",
		symbol: "POL",
		chainId: 80002,
		rpcUrl: "https://rpc-amoy.polygon.technology",
		explorerUrl: "https://amoy.polygonscan.com",
		icon: "🟣",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: true,
	},
	[Network.BSC_TESTNET]: {
		id: Network.BSC_TESTNET,
		name: "BSC Testnet",
		symbol: "tBNB",
		chainId: 97,
		rpcUrl: "https://data-seed-prebsc-1-s1.binance.org:8545",
		explorerUrl: "https://testnet.bscscan.com",
		icon: "🟡",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: true,
	},
	[Network.ARBITRUM_SEPOLIA]: {
		id: Network.ARBITRUM_SEPOLIA,
		name: "Arbitrum Sepolia",
		symbol: "ETH",
		chainId: 421614,
		rpcUrl: "https://sepolia-rollup.arbitrum.io/rpc",
		explorerUrl: "https://sepolia.arbiscan.io",
		icon: "🔵",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: true,
	},
	[Network.OPTIMISM_SEPOLIA]: {
		id: Network.OPTIMISM_SEPOLIA,
		name: "Optimism Sepolia",
		symbol: "ETH",
		chainId: 11155420,
		rpcUrl: "https://sepolia.optimism.io",
		explorerUrl: "https://sepolia-optimism.etherscan.io",
		icon: "🔴",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: true,
	},
	[Network.AVALANCHE_FUJI]: {
		id: Network.AVALANCHE_FUJI,
		name: "Avalanche Fuji",
		symbol: "AVAX",
		chainId: 43113,
		rpcUrl: "https://api.avax-test.network/ext/bc/C/rpc",
		explorerUrl: "https://testnet.snowtrace.io",
		icon: "🔺",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: true,
	},
	[Network.BASE_SEPOLIA]: {
		id: Network.BASE_SEPOLIA,
		name: "Base Sepolia",
		symbol: "ETH",
		chainId: 84532,
		rpcUrl: "https://sepolia.base.org",
		explorerUrl: "https://sepolia.basescan.org",
		icon: "🔷",
		isEVM: true,
		decimals: 18,
		derivationPath: "m/44'/60'/0'/0/0",
		isTestnet: true,
	},
	[Network.SOLANA_DEVNET]: {
		id: Network.SOLANA_DEVNET,
		name: "Solana Devnet",
		symbol: "SOL",
		rpcUrl: "https://api.devnet.solana.com",
		explorerUrl: "https://solscan.io/?cluster=devnet",
		icon: "◎",
		isEVM: false,
		decimals: 9,
		derivationPath: "m/44'/501'/0'/0'",
		isTestnet: true,
	},
	[Network.BITCOIN_TESTNET]: {
		id: Network.BITCOIN_TESTNET,
		name: "Bitcoin Testnet",
		symbol: "tBTC",
		rpcUrl: "",
		explorerUrl: "https://blockstream.info/testnet",
		icon: "₿",
		isEVM: false,
		decimals: 8,
		derivationPath: "m/84'/1'/0'/0/0",
		isTestnet: true,
	},
};

// Фильтры для сетей
export const getNetworksByMode = (mode: NetworkMode) =>
	Object.values(NETWORKS).filter((n) =>
		mode === "testnet" ? n.isTestnet : !n.isTestnet,
	);

export const getEVMNetworks = (mode: NetworkMode) =>
	getNetworksByMode(mode).filter((n) => n.isEVM);

export const MAINNET_NETWORKS = getNetworksByMode("mainnet");
export const TESTNET_NETWORKS = getNetworksByMode("testnet");
export const EVM_NETWORKS = Object.values(NETWORKS).filter((n) => n.isEVM);
export const ALL_NETWORKS = Object.values(NETWORKS);
